[package]
name = "rand_field_derive"
version = "0.1.0"
authors = ["Frederic Desgreniers <fredericdesgreniers@gmail.com>"]
[lib]
proc-macro=true


[dependencies]
syn = {version="*", features=["extra-traits"]}
quote = "*"
proc-macro2 = "*"
rand = "*"